// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:0f027ef3-9f62-48cb-882e-3870dc27e826",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_xOMS7QVwm",
    "aws_user_pools_web_client_id": "cmiqgrt5ordgpv4uefjsgmotq",
    "aws_mobile_analytics_app_id": "beca5c6b34b743c5b795a4896dfd6bf3",
    "aws_mobile_analytics_app_region": "us-east-1",
    "aws_content_delivery_bucket": "myapp-20181108165202--hostingbucket",
    "aws_content_delivery_bucket_region": "eu-west-1",
    "aws_content_delivery_url": "http://myapp-20181108165202--hostingbucket.s3-website-eu-west-1.amazonaws.com",
    "aws_dynamodb_all_tables_region": "eu-west-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "Users",
            "region": "eu-west-1"
        },
        {
            "tableName": "Projects",
            "region": "eu-west-1"
        }
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "usersAPI",
            "endpoint": "https://of93ldnuif.execute-api.eu-west-1.amazonaws.com/Prod",
            "region": "eu-west-1"
        },
        {
            "name": "projectsAPI",
            "endpoint": "https://tr3ntd4v73.execute-api.eu-west-1.amazonaws.com/Prod",
            "region": "eu-west-1"
        }
    ]
};


export default awsmobile;
